# Override configuration from https://github.com/jenkins-x/jenkins-x-platform/blob/master/jenkins-x-platform/values.yaml
chartmuseum:
  persistence:
    size: 20Gi
jenkins:
  Persistence:
    Size: 20Gi
monocular:
  mongodb:
    persistence:
      size: 20Gi
nexus:
  persistence:
    size: 20Gi
# Tekton config
# Because tekton is installed individually and not part of the platform its config needs to be in the top level
pvc:
  size: 20Gi
